[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.poetry]
name = "discapty"
version = "2.0.0"
description = "DisCapTy help you generate obfuscated images, leaving your code easy."
authors = ["Predeactor <predeactor0@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Predeactor/DisCapTy"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.9"
pillow = {version = "^8.4.0"}
pydantic = "^1.9.1"

# Extras: Docs
furo = {version = "^2022.2.14", extras = ["docs"]}
Sphinx = {version = "^4.4.0", extras = ["docs"]}

# Extras: Dev
black = {version = "^22.1.0", extras = ["dev"]}
isort = {version = "^5.10.1", extras = ["dev"]}
tox = {version = "^3.24.5", extras = ["dev"]}

[tool.poetry.urls]
homepage = "https://github.com/Predeactor/DisCapTy"
repository = "https://github.com/Predeactor/DisCapTy"


[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
mypy = "^0.960"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
