# Preparing release consist of:
# - Check version of package, if it respect semantic ver.

name: Prepare Release
on:
  workflow_call:

jobs:
  pre-release:
    name: Review this part before approval
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install & configure Poetry
    - name: Install Poetry
      run: pipx install poetry==1.7.1

    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.10'
        cache: 'poetry'

    # Install DisCapTy itself
    - name: Install dependencies and DisCapTy
      run: poetry install -n

    # Install requests manually
    - name: Install requests
      run: poetry run pip install requests  # Pip is much more faster than Poetry

    # Run the main script
    - name: Run script
      run: poetry run python ./.github/scripts/pre_release.py
