name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
    - "*"

jobs:

  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml

  pre-release:
    name: Prepare release
    needs: test
    uses: ./.github/workflows/prepare-release.yml

  deploy:
    # if: github.repository == 'Predeactor/DisCapTy'
    runs-on: ubuntu-latest
    environment: release
    name: Deploy DisCapTy to PyPi.
    needs: pre-release

    steps:
    - uses: actions/checkout@v2

    # Install & configure Poetry
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install & configure Poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    # Load cached venv
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    # Install external dependencies & DisCapTy
    - name: Install dependencies
      run: poetry install -n

    - name: Build and publish
      run: poetry debug
      # run: poetry publish --build --username "__token__" --password "${{ secrets.PYPI_API_TOKEN }}"
