name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pre-release:
    name: Prepare release
    uses: ./.github/workflows/prepare-release.yml

  deploy:
    if: github.repository == 'madebylydia/DisCapTy'
    runs-on: ubuntu-latest
    environment: release
    name: Deploy DisCapTy to PyPi.
    needs: pre-release

    steps:
    - uses: actions/checkout@v4

    # Install & configure Poetry
    - name: Install Poetry
      uses: pipx install poetry==1.7.1

    # Install Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'

    # Install external dependencies & DisCapTy
    - name: Install dependencies and DisCapTy
      run: poetry install -n

    - name: Build package
      run: poetry build -n

    - name: Publish to PyPi
      run: |
        poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
        poetry publish -n
