name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
     - "*"

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml

  deploy:
    # if: github.repository == 'Predeactor/DisCapTy'
    runs-on: ubuntu-latest
    name: Deploy DisCapTy to PyPi.
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python & Poetry
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.1.13'
      run: poetry install

    - name: Build and publish
      run: poetry debug
