name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
     - "*"

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml

  deploy:
    # if: github.repository == 'Predeactor/DisCapTy'
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      uses: ./.github/workflows/tests.yml

    - name: Is Poetry installed?
      run: poetry --help


    - name: Build and publish
      run: echo "Publishing to PyPi logic."
